#!/bin/bash
#############################################
# OBSIDIAN INITRAMFS REBUILD SCRIPT
# Regenerates initramfs with live-boot
# support for the Obsidian OS ISO
#############################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

#############################################
# CONFIG
#############################################

ROOTFS_DIR="${ROOTFS_DIR:-$PROJECT_DIR/rootfs}"
ISO_DIR="${ISO_DIR:-$PROJECT_DIR/iso}"
OUTPUT_DIR="${OUTPUT_DIR:-$ISO_DIR/OBSIDIAN}"
WORK_DIR="/tmp/initramfs-rebuild-$$"

# Kernel version detection
KERNEL_VERSION="${KERNEL_VERSION:-}"

# Live-boot configuration
LIVE_MEDIA_PATH="${LIVE_MEDIA_PATH:-/OBSIDIAN}"
SQUASHFS_FILENAME="${SQUASHFS_FILENAME:-filesystem.squashfs}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

#############################################
# HELPER FUNCTIONS
#############################################

log_step() {
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}📋 $1${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

cleanup() {
    echo -e "${BLUE}🧹 Cleaning up...${NC}"
    rm -rf "$WORK_DIR"
}
trap cleanup EXIT

#############################################
# SETUP
#############################################

log_step "Checking Prerequisites"

# Verify rootfs exists
if [ ! -d "$ROOTFS_DIR" ]; then
    log_error "Root filesystem not found: $ROOTFS_DIR"
    exit 1
fi

# Check required tools
for tool in chroot update-initramfs mkinitramfs; do
    if ! command -v "$tool" &>/dev/null && [ ! -x "$ROOTFS_DIR/usr/sbin/$tool" ]; then
        log_warning "Tool not found: $tool"
    fi
done

# Detect kernel version if not specified
if [ -z "$KERNEL_VERSION" ]; then
    if [ -d "$ROOTFS_DIR/lib/modules" ]; then
        KERNEL_VERSION=$(ls -1 "$ROOTFS_DIR/lib/modules" | sort -V | tail -1)
    fi
    
    if [ -z "$KERNEL_VERSION" ]; then
        log_error "Cannot detect kernel version. Set KERNEL_VERSION env var."
        exit 1
    fi
fi

log_info "Root filesystem: $ROOTFS_DIR"
log_info "Kernel version: $KERNEL_VERSION"
log_info "Output directory: $OUTPUT_DIR"

mkdir -p "$WORK_DIR" "$OUTPUT_DIR"

#############################################
# VALIDATE LIVE-BOOT INSTALLATION
#############################################

log_step "Validating Live-boot Configuration"

# Check live-boot is installed
if [ ! -d "$ROOTFS_DIR/usr/lib/live/boot" ]; then
    log_error "live-boot not installed in rootfs"
    log_info "Install with: chroot $ROOTFS_DIR apt install live-boot live-boot-initramfs-tools"
    exit 1
fi
log_success "live-boot is installed"

# Check live-boot initramfs hooks
HOOK_FILES=(
    "$ROOTFS_DIR/usr/share/initramfs-tools/hooks/live"
    "$ROOTFS_DIR/usr/share/initramfs-tools/scripts/live"
    "$ROOTFS_DIR/usr/share/initramfs-tools/scripts/live-bottom"
    "$ROOTFS_DIR/usr/share/initramfs-tools/scripts/live-premount"
)

for hook in "${HOOK_FILES[@]}"; do
    if [ -e "$hook" ] || [ -d "$hook" ]; then
        log_success "Found: $(basename "$hook")"
    else
        log_warning "Missing: $hook"
    fi
done

# Check live.cfg configuration
LIVE_CFG_DIR="$ROOTFS_DIR/etc/live/boot.conf.d"
mkdir -p "$LIVE_CFG_DIR"

#############################################
# CONFIGURE LIVE-BOOT
#############################################

log_step "Configuring Live-boot for Obsidian"

# Create Obsidian-specific live-boot configuration
cat > "$ROOTFS_DIR/etc/live/boot.conf" << EOF
# Obsidian OS Live-boot Configuration
# This file is generated by rebuild-initramfs.sh

LIVE_MEDIA_PATH="$LIVE_MEDIA_PATH"
LIVE_MEDIA_DESCRIPTORFILE=".disk/info"
EOF

# Create additional configuration snippets
cat > "$LIVE_CFG_DIR/obsidian.conf" << EOF
# Obsidian OS specific settings

# Path to squashfs inside ISO
LIVE_MEDIA_PATH="$LIVE_MEDIA_PATH"

# Hostname for live session
LIVE_HOSTNAME="obsidian"

# Disable persistence by default (forensic-friendly)
PERSISTENCE="false"

# Mount options for squashfs
LIVE_ROOT_FSTYPE="squashfs"
EOF

log_success "Live-boot configuration written"

# Verify squashfs path consistency
log_info "Validating squashfs path configuration..."

# Check isolinux.cfg for correct paths
ISOLINUX_CFG="$ISO_DIR/isolinux/isolinux.cfg"
if [ -f "$ISOLINUX_CFG" ]; then
    if grep -q "live-media-path=" "$ISOLINUX_CFG"; then
        CONFIGURED_PATH=$(grep -o "live-media-path=[^ ]*" "$ISOLINUX_CFG" | head -1 | cut -d= -f2)
        if [ "$CONFIGURED_PATH" = "$LIVE_MEDIA_PATH" ]; then
            log_success "isolinux.cfg: live-media-path=$CONFIGURED_PATH (matches)"
        else
            log_warning "isolinux.cfg: live-media-path=$CONFIGURED_PATH (expected: $LIVE_MEDIA_PATH)"
        fi
    else
        log_warning "isolinux.cfg: No live-media-path parameter found"
    fi
fi

# Check grub.cfg for correct paths
GRUB_CFG="$ISO_DIR/boot/grub/grub.cfg"
if [ -f "$GRUB_CFG" ]; then
    if grep -q "live-media-path=" "$GRUB_CFG"; then
        CONFIGURED_PATH=$(grep -o "live-media-path=[^ ]*" "$GRUB_CFG" | head -1 | cut -d= -f2)
        log_info "grub.cfg: live-media-path=$CONFIGURED_PATH"
    fi
fi

#############################################
# SETUP CHROOT ENVIRONMENT
#############################################

log_step "Setting Up Chroot Environment"

# Mount required filesystems for chroot
log_info "Mounting proc/sys/dev for chroot..."
mount -t proc /proc "$ROOTFS_DIR/proc" 2>/dev/null || true
mount -t sysfs /sys "$ROOTFS_DIR/sys" 2>/dev/null || true
mount --bind /dev "$ROOTFS_DIR/dev" 2>/dev/null || true
mount --bind /dev/pts "$ROOTFS_DIR/dev/pts" 2>/dev/null || true

# Cleanup function for mounts
unmount_chroot() {
    umount "$ROOTFS_DIR/dev/pts" 2>/dev/null || true
    umount "$ROOTFS_DIR/dev" 2>/dev/null || true
    umount "$ROOTFS_DIR/sys" 2>/dev/null || true
    umount "$ROOTFS_DIR/proc" 2>/dev/null || true
}
trap "unmount_chroot; cleanup" EXIT

log_success "Chroot environment ready"

#############################################
# BUILD INITRAMFS
#############################################

log_step "Building Initramfs"

# Backup existing initrd
if [ -f "$OUTPUT_DIR/initrd" ]; then
    cp "$OUTPUT_DIR/initrd" "$OUTPUT_DIR/initrd.bak"
    log_info "Backed up existing initrd"
fi

# Build the new initramfs
INITRAMFS_OUTPUT="$WORK_DIR/initrd.img-$KERNEL_VERSION"

log_info "Running mkinitramfs for kernel $KERNEL_VERSION..."

# Use chroot to build initramfs
chroot "$ROOTFS_DIR" /bin/bash -c "
    export PATH=/usr/sbin:/usr/bin:/sbin:/bin
    
    # Ensure live-boot hooks are executable
    chmod +x /usr/share/initramfs-tools/hooks/live 2>/dev/null || true
    
    # Build initramfs with verbose output
    mkinitramfs -o /tmp/initrd.img-$KERNEL_VERSION $KERNEL_VERSION
    
    echo 'Initramfs modules included:'
    lsinitramfs /tmp/initrd.img-$KERNEL_VERSION 2>/dev/null | grep -E '(live|squashfs|loop)' | head -20 || true
"

# Copy initramfs out of chroot
if [ -f "$ROOTFS_DIR/tmp/initrd.img-$KERNEL_VERSION" ]; then
    cp "$ROOTFS_DIR/tmp/initrd.img-$KERNEL_VERSION" "$INITRAMFS_OUTPUT"
    rm -f "$ROOTFS_DIR/tmp/initrd.img-$KERNEL_VERSION"
    log_success "Initramfs built successfully"
else
    log_error "Failed to build initramfs"
    exit 1
fi

#############################################
# VALIDATE INITRAMFS
#############################################

log_step "Validating Initramfs Contents"

# Check initramfs size
INITRAMFS_SIZE=$(stat -c%s "$INITRAMFS_OUTPUT")
log_info "Initramfs size: $(numfmt --to=iec $INITRAMFS_SIZE)"

if [ "$INITRAMFS_SIZE" -lt 10000000 ]; then
    log_warning "Initramfs is suspiciously small (<10MB)"
fi

# Extract and validate initramfs contents
EXTRACT_DIR="$WORK_DIR/initramfs-extract"
mkdir -p "$EXTRACT_DIR"

log_info "Extracting initramfs for validation..."
cd "$EXTRACT_DIR"

# Handle different compression formats
if file "$INITRAMFS_OUTPUT" | grep -q "gzip"; then
    zcat "$INITRAMFS_OUTPUT" | cpio -idm 2>/dev/null
elif file "$INITRAMFS_OUTPUT" | grep -q "Zstandard"; then
    zstd -d < "$INITRAMFS_OUTPUT" | cpio -idm 2>/dev/null
elif file "$INITRAMFS_OUTPUT" | grep -q "XZ"; then
    xz -d < "$INITRAMFS_OUTPUT" | cpio -idm 2>/dev/null
else
    # Try as plain cpio
    cpio -idm < "$INITRAMFS_OUTPUT" 2>/dev/null || true
fi

# Verify live-boot scripts are included
REQUIRED_SCRIPTS=(
    "scripts/live"
    "scripts/live-bottom"
    "scripts/live-premount"
    "lib/live/boot"
)

MISSING_SCRIPTS=0
for script in "${REQUIRED_SCRIPTS[@]}"; do
    if [ -e "$EXTRACT_DIR/$script" ] || [ -d "$EXTRACT_DIR/$script" ]; then
        log_success "✓ $script"
    else
        log_warning "✗ $script (missing)"
        ((MISSING_SCRIPTS++))
    fi
done

# Check for squashfs support
if [ -f "$EXTRACT_DIR/lib/modules/$KERNEL_VERSION/kernel/fs/squashfs/squashfs.ko"* ] || \
   grep -rq "squashfs" "$EXTRACT_DIR/conf" 2>/dev/null; then
    log_success "Squashfs support available"
else
    log_warning "Squashfs module may be missing"
fi

# Check for loop device support
if [ -f "$EXTRACT_DIR/lib/modules/$KERNEL_VERSION/kernel/drivers/block/loop.ko"* ] || \
   [ -e "$EXTRACT_DIR/dev/loop0" ]; then
    log_success "Loop device support available"
else
    log_warning "Loop device support may be missing"
fi

#############################################
# INSTALL INITRAMFS
#############################################

log_step "Installing Initramfs"

# Copy to output directory
cp "$INITRAMFS_OUTPUT" "$OUTPUT_DIR/initrd"
log_success "Installed: $OUTPUT_DIR/initrd"

# Also update the rootfs boot directory
if [ -d "$ROOTFS_DIR/boot" ]; then
    cp "$INITRAMFS_OUTPUT" "$ROOTFS_DIR/boot/initrd.img-$KERNEL_VERSION"
    
    # Update symlink
    ln -sf "initrd.img-$KERNEL_VERSION" "$ROOTFS_DIR/initrd.img"
    log_success "Updated: $ROOTFS_DIR/boot/initrd.img-$KERNEL_VERSION"
fi

# Generate checksums
cd "$OUTPUT_DIR"
sha256sum initrd > initrd.sha256
log_info "Checksum: $(cat initrd.sha256)"

#############################################
# SUMMARY
#############################################

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}🎉 INITRAMFS REBUILD COMPLETE${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 Output:         $OUTPUT_DIR/initrd"
echo "📊 Size:           $(numfmt --to=iec $INITRAMFS_SIZE)"
echo "🔐 SHA256:         $(cut -d' ' -f1 < "$OUTPUT_DIR/initrd.sha256")"
echo "🐧 Kernel:         $KERNEL_VERSION"
echo "📁 Live Path:      $LIVE_MEDIA_PATH"
echo ""

if [ "$MISSING_SCRIPTS" -gt 0 ]; then
    echo -e "${YELLOW}⚠️  Warning: $MISSING_SCRIPTS live-boot components may be missing${NC}"
    echo "   Consider reinstalling live-boot-initramfs-tools"
    echo ""
fi

echo "Next steps:"
echo "  1. Rebuild the ISO with: ./scripts/build-obsidian-iso.sh"
echo "  2. Test with QEMU:       ./scripts/qemu-boot-test.sh"
echo "  3. Test with VirtualBox: ./scripts/virtualbox-boot-test.sh"
echo ""

# Report for CI
if [ -n "${GITHUB_OUTPUT:-}" ]; then
    echo "initrd_path=$OUTPUT_DIR/initrd" >> "$GITHUB_OUTPUT"
    echo "initrd_size=$INITRAMFS_SIZE" >> "$GITHUB_OUTPUT"
    echo "kernel_version=$KERNEL_VERSION" >> "$GITHUB_OUTPUT"
fi

exit 0
